<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.20" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bison.Models\Bison.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="resources/**/*"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bison.Database.Tests"/>
  </ItemGroup>

</Project>
