name: Issues Management

on:
    issues:
        types: [opened]
    # issue_comment: # not used currently, as the two that rely on it are commented out
    #     types: [created]

env:
    DOTNET_VERSION: "8.0.x"

jobs:
    weekly_issue_opened:
        name: Weekly Issue Opened
        if: ${{ github.event.action == 'opened' && startsWith(github.event.issue.title, 'weekly/') }}
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NUMBER: ${{ github.event.issue.number }}
        steps:
            - name: "Add weekly label & project"
              run: gh issue edit $NUMBER -t Task --add-project "ITU-BDSA2026-GROUP17 Bison" --add-label "weekly"

            - name: "Add to current iteration"
              run: gh project item-edit --url "$URL" --iteration-id "@current"
              env:
                  URL: ${{ github.event.issue.url }}

            - name: "Create PR"
              run: |-
                  gh pr create --base main --head dev --draft --title "$TITLE" --label "weekly,$LABELS" 
                  --assignee "$USER" --project "ITU-BDSA2026-GROUP17 Bison" -b "Closes $NUMBER
                  # Weekly PR
                  This PR has been autogenerated by GitHub Actions.
                  Please view the linked issue for when this PR should be merged.

                  This PR has automatically been assigned to @$USER"
              env:
                  TITLE: ${{ github.event.issue.title }}
                  LABELS: ${{ join(github.event.issue.labels.*.name, ",") }}
                  USER: ${{ github.event.issue.user.login }}

    # pr_commented:
        # # This job only runs for pull request comments (could be useful later)
        # name: PR comment
        # if: ${{ github.event.action == 'created' && github.event.issue.pull_request }}
        # runs-on: ubuntu-latest
        # steps:
            # - run: |
                  # echo A comment on PR $NUMBER
              # env:
                  # NUMBER: ${{ github.event.issue.number }}

    # issue_commented:
        # # This job only runs for issue comments (could be useful later)
        # name: Issue comment
        # if: ${{ github.event.action == 'created' && !github.event.issue.pull_request }}
        # runs-on: ubuntu-latest
        # steps:
            # - run: |
                  # echo A comment on issue $NUMBER
              # env:
                  # NUMBER: ${{ github.event.issue.number }}
