name: Issues Management

on:
    issues:
        types: [opened]
    # issue_comment: # not used currently, as the two that rely on it are commented out
    #     types: [created]

env:
    DOTNET_VERSION: "8.0.x"

jobs:
    weekly_issue_opened:
        name: Weekly Issue Opened
        if: ${{ github.event.action == 'opened' && startsWith(github.event.issue.title, 'weekly/') }}
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NUMBER: ${{ github.event.issue.number }}
        steps:
            - id: "iteration"
              name: "Get latest iteration"
              run: |
                  RESULT=$(gh api graphql -F login='${{ github.repository_owner }}' -f query='
                    query($login:String!) {
                        organization(login:$login) {
                            projectsV2(first:1) {
                                nodes {
                                    title,
                                    field(name:"Iteration") {
                                        ... on ProjectV2IterationField {
                                            configuration {
                                                iterations { title, id }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                  ' | jq '.data.organization.projectsV2.nodes[0]')
                  echo "iter=$(echo $RESULT | jq -r '.field.configuration.iterations[0].id')" >> $GITHUB_OUTPUT
                  echo "project=$(echo $RESULT | jq -r '.title')" >> $GITHUB_OUTPUT

            - name: "Add weekly label & project"
              run: gh issue edit $NUMBER -t Task --add-project "$PROJECT" --add-label "weekly"
              env:
                  PROJECT: ${{ steps.iteration.outputs.project }}

            - name: "Add to current iteration"
              run: gh project item-edit 1 --owner "${{ github.repository_owner }}" --url "$URL" --field iteration --iteration-id "$ITERATION"
              env:
                  URL: ${{ github.event.issue.url }}
                  ITERATION: ${{ steps.iteration.outputs.iter }}

            - name: "Create PR"
              run: |-
                  PR_URL=$(gh pr create --base main --head dev --draft --title "$TITLE" --label "weekly,$LABELS"\
                  --assignee "$USER" --project "$PROJECT" --body "Closes $NUMBER
                  # Weekly PR
                  This PR has been autogenerated by GitHub Actions.
                  Please view the linked issue for when this PR should be merged.

                  This PR has automatically been assigned to @$USER")
                  echo "Created PR at $PR_URL"
                  gh project item-edit 1 --owner "${{ github.repository_owner }}" --url "$PR_URL" --field iteration --iteration-id "$ITERATION"
              env:
                  TITLE: ${{ github.event.issue.title }}
                  LABELS: ${{ join(github.event.issue.labels.*.name, ',') }}
                  USER: ${{ github.event.issue.user.login }}
                  PROJECT: ${{ steps.iteration.outputs.project }}
                  ITERATION: ${{ steps.iteration.outputs.iter }}

    # pr_commented:
    # # This job only runs for pull request comments (could be useful later)
    # name: PR comment
    # if: ${{ github.event.action == 'created' && github.event.issue.pull_request }}
    # runs-on: ubuntu-latest
    # steps:
    # - run: |
    # echo A comment on PR $NUMBER
    # env:
    # NUMBER: ${{ github.event.issue.number }}

    # issue_commented:
    # # This job only runs for issue comments (could be useful later)
    # name: Issue comment
    # if: ${{ github.event.action == 'created' && !github.event.issue.pull_request }}
    # runs-on: ubuntu-latest
    # steps:
    # - run: |
    # echo A comment on issue $NUMBER
    # env:
    # NUMBER: ${{ github.event.issue.number }}
